include:
# Dongle
  - board: seeeduino_xiao_ble
    shield: lotus581_dongle prospector_adapter
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Lotus581Dongle\" -DCONFIG_ZMK_SLEEP=n -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n -DZMK_BLE_IS_CENTRAL=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    snippet: studio-rpc-usb-uart zmk-usb-logging usb_os_detector
# Left half
  - board: nice_nano_v2
    shield: lotus581_left
    snippet: zmk-usb-logging
# Right half
  - board: nice_nano_v2
    shield: lotus581_right
    snippet: zmk-usb-logging
# Reset
 # - board: nice_nano_v2
  #  shield: settings_reset
  #- board: seeeduino_xiao_ble
   # shield: settings_reset