manifest:
  remotes:
    - name: Samsuper12
      url-base: https://github.com/Samsuper12
    - name: carrefinho
      url-base: https://github.com/carrefinho
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: prospector-zmk-module
      remote: carrefinho
      revision: main
    - name: os-layer-zmk-module
      remote: Samsuper12
      revision: usb_os_detector
  self:
    path: config
